#!/bin/bash




check_service=`sudo systemctl status mariadb | grep -o 'Active: active'`

if [ "$check_service" == "Active: active" ];then
	shas=`cat shell_sha256.txt`
	for sha in $shas;do
		mysql --execute="use malware;INSERT INTO shell (sha) VALUES ('$sha')"
	done


	echo "Files Sha is Done"
else
	sudo systemctl start mariadb
	shas=`cat shell_sha256.txt`
	for sha in $shas;do
		mysql --execute="use malware;INSERT INTO shell (sha) VALUES ('$sha')"
	done

fi
