#!/bin/bash

# Installation script for LinuxAV-Solutions EDR

# Copy files
sudo cp myEDR /usr/local/bin/myEDR
sudo chmod 755 /usr/local/bin/myEDR

# Create config directory
sudo mkdir -p /etc/myEDR
sudo cp myEDR.conf ~/.myEDR/config/myEDR.conf
sudo ln -s ~/.myEDR/config/myEDR.conf /etc/myEDR/myEDR.conf

# Create app directory
sudo mkdir -p /var/lib/myEDR/{quarantine,signatures,rules,baseline}

# Install systemd service
sudo cp myEDR.service /etc/systemd/system/
sudo systemctl daemon-reload

# Initialize
sudo /usr/local/bin/myEDR --edr-baseline

# Start service
sudo systemctl enable myEDR
sudo systemctl start myEDR

echo "LinuxAV-Solutions EDR installed and started"
