#!/usr/bin/bash

green=$'\e[1;32m' # green color


cd /tmp

wget https://github.com/KooshaYeganeh/KYGnus-AV/archive/refs/heads/main.zip

unzip main.zip

cd KYGnus-AV-main/

sudo cp KYGnusAV /usr/bin

sudo rm -rf /tmp/KYGnus-AV-main

sudo rm /tmp/main.zip

cd 

echo "$green => KYGnusAV Installed Successfully <="
