#!/bin/bash


start_system(){
	cd /home/$USER/.KYGnus-Guard-Community
	source venv/bin/activate

<<python
Note : if You User Debian Base systems Like Ubunjtu or Lubuntu or Others
Yoy should Change python with python3 tu Run App.in RedHat Base systems Like
Fedora python command Runs Default Python3
python

	python app.py
}



stop_system(){
	pkill -15 python
}



help_page(){
	echo "** KYGnus Guard Comminity **"
	echo -e " kyguard"
	echo -e "\t --stop : Stop KYGnus Guard app"
	echo -e "\t --start: Start KYgnus Guard app"
	echo -e "\t --help : help Page"
}



if [ "$0" == "kyguard" ];then
	if [ "$1" == "--stop" ];then
		stop_system
	elif [ "$1" == "--start" ];then
		start_system
	elif [ "$1" == "--help" ];then
		help_page
	else
		echo "Unknown command !!! Please check Help Page"
		echo "kyguard --help"
	fi
else
	echo "Unknown kyguard command"
fi
